version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5083:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;User=root;Password=root;Database=book;
    networks:
      - backendnet

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: book
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backendnet

volumes:
  dbdata:

networks:
  backendnet: